layout: {qmk_keyboard: ergodox_ez/base, qmk_layout: LAYOUT_ergodox_pretty}
layers:
  base_layer: ['=', '1', '2', '3', '4', '5', keypad, mod, '6', '7', '8', '9', '0', '-', TAB, Q, W, E, R, T, base_layer, mouse, Y, U, I, O, P, \, ESC, A, S, D, F,
    G, colemak_layer, '', H, J, K, L, ;, '''', LSHFT, Z, X, C, V, B, N, M, ',', ., /, RSHFT, fn, '`', CAPS, LEFT, RIGHT, UP, DOWN, '[', ']', fn, LCTRL, LALT, LGUI,
    RCTRL, BSPC, DEL, HOME, PG UP, ENTER, SPACE, END, PG DN]
  colemak_layer: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', Q, W, F, P, B, '', '', J, L, U, Y, '''', \, '', A, R, S, T, G, '', '', M, N, E, I, O,
    /, '', Z, X, C, D, V, K, H, ',', ., ;, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
  keypad: ['', '', '', '', '', '', '', '', '', KP NUM, KP EQUAL, KP DIVIDE, KP MULTIPLY, '', '', '', '', '', '', '', '', '', '', KP 7, KP 8, KP 9, KP MINUS, '', '',
    '', '', '', '', '', '', '', '', KP 4, KP 5, KP 6, KP PLUS, '', '', '', '', '', '', '', '', KP 1, KP 2, KP 3, KP ENTER, '', '', '', '', '', '', KP 0, '', KP DOT,
    '', '', '', '', '', '', '', '', '', '', '', '', '', '']
  fn:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - ''
  - ''
  - F7
  - F8
  - F9
  - F10
  - F11
  - F12
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  mod:
  - ''
  - BT 0
  - BT 1
  - BT 2
  - BT 3
  - BT 4
  - ''
  - {type: held}
  - BT 0
  - BT 1
  - BT 2
  - BT 3
  - BT 4
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&bootloader'
  - '&bootloader'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&bl BL_INC'
  - '&bl BL_DEC'
  - '&bl BL_INC'
  - '&bl BL_DEC'
  - ''
  - ''
  - ''
  - BT CLR
  - BT CLR
  - BT CLR
  - BT CLR
  - ''
  - '&bl BL_TOG'
  - ''
  - ''
  - '&bl BL_TOG'
  - ''
  - ''
  - ''
  mouse: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '&mmv MOVE_HOR(-600)', '&mmv MOVE_HOR(600)', '&mmv MOVE_VERT(-600)', '&mmv MOVE_VERT(600)',
    '', '', '', '&mkp MB3', '', '', '&mkp MB3', '&mkp MB1', '&mkp MB2', '&mwh SCROLL_HOR(-10)', '&mwh SCROLL_VERT(10)', '&mkp MB2', '&mkp MB1', '&mwh SCROLL_HOR(10)',
    '&mwh SCROLL_VERT(-10)']
